disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Ionic Stacks"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "January 2 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
   copyright = "&copy; 2026 Yurou Celine Xiao"

[params.author]
   name = "Yurou Celine Xiao"
#   email = "youremail@example.com"
   image = "images/celine/2025profile.jpeg"
   imageQuality = 96
   headline = "Under construction..."
   bio = "A little bit about you"
   links = [
#     { email = "mailto:hello@your_domain.com" },
#     { link = "https://link-to-some-website.com/" },
#     { discord = "https://discord.gg/invitecode" },
#     { github = "https://github.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { instagram = "https://instagram.com/username" },
     { linkedin = "https://www.linkedin.com/in/celine-xiao/" },
#     { orcid = "https://orcid.org/userid" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { spotify = "https://open.spotify.com/user/userid" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { youtube = "https://youtube.com/username" },
   ]
