# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

# 1.0 Carbon Dioxide Removal (CDR)
[[main]]
  name = 'CDR'
  pageRef = "tech/cdr"
  identifier = "cdr"
  weight = 10

# 1.1 Direct Air Capture (DAC)
[[main]]
  name = "Air"
  pageRef = "tech/cdr/dac"
  parent = "cdr"
  weight = 1

# 1.2 Marine Carbon Dioxide Removal (mCDR)
[[main]]
  name = "Ocean"
  pageRef = "tech/cdr/mcdr"
  parent = "cdr"
  weight = 2

# 2.0 Power-to-X (PtX)
[[main]]
  name = 'PtX'
  pageRef = "tech/ptx"
  identifier = "ptx"
  weight = 20

# 2.1 Syngas
[[main]]
  name = "Syngas"
  pageRef = "tech/ptx/syngas"
  parent = "ptx"
  weight = 1

# 2.2 eFuels
[[main]]
  name = "eFuels"
  pageRef = "tech/ptx/efuels"
  parent = "ptx"
  weight = 2

# 2.3 eChemicals
[[main]]
  name = "eChemicals"
  pageRef = "tech/ptx/echemicals"
  parent = "ptx"
  weight = 3

# 3.0 Industrial Decarbonization
[[main]]
  name = 'Industry'
  pageRef = "tech/industry"
  identifier = "industry"
  weight = 30

# 3.1 Minerals
[[main]]
  name = "Minerals"
  pageRef = "tech/industry/minerals"
  parent = "industry"
  weight = 1

# 3.2 Cement
[[main]]
  name = "Cement"
  pageRef = "tech/industry/cement"
  parent = "industry"
  weight = 2

# 3.3 Water Desalination
[[main]]
  name = "Desalination"
  pageRef = "tech/industry/desalination"
  parent = "industry"
  weight = 3

#[[main]]
#  name = 'PtX'
#  pageRef = "categories/ptx"
#  weight = 20

#[[main]]
#  name = 'Industry'
#  pageRef = "categories/industry"
#  weight = 30

#[[main]]
#  name = "Blog"
#  pageRef = "posts"
#  weight = 10

#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
